### ISSUE TITLE
cannot execute binary files of phenotypeseeker

### ISSUE THREAD

**Issue by philt31** [bioinfo-ut/PhenotypeSeeker#13]
I'm getting the following errors when I try and run the example scripts on my mac, any ideas why it wont execute the binary files?
Generating the k-mer lists for input samples:
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	1 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	8 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	9 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	10 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	11 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	12 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	16 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	17 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	18 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	19 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	20 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	22 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	24 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	25 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	26 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	27 of 30 lists generated./bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
	30 of 30 lists generated.
Generating the k-mer feature vector.
/bin/sh: /usr/local/bin/glistmaker: cannot execute binary file
Mapping samples to the feature vector space:
/bin/sh: /usr/local/bin/glistquery: cannot execute binary file
/bin/sh: /usr/local/bin/glistquery: cannot execute binary file
/bin/sh: /usr/local/bin/glistquery: cannot execute binary file
/bin/sh: /usr/local/bin/glistquery: cannot execute binary file
/bin/sh: /usr/local/bin/glistquery: cannot execute binary file
/bin/sh: /usr/local/bin/glistquery: cannot execute binary file
/bin/sh: /usr/local/bin/glistquery: cannot execute binary file
/bin/sh: /usr/local/bin/glistquery: cannot execute binary file
rm: K-mer_lists/VL_0004_13.list: No such file or directory
rm: K-mer_lists/VL_0216_13.list: No such file or directory

**Comment by bioinfo-ut** [comment]
Usually that error message means Linux doesn't recognize the file as a shell script or as an executable file.
Typically the cause is running an executable on the wrong architecture.

Which Linux do you use and which CPU?

**Comment by erkiaun** [comment]
These binary files are compiled for Linux operating systems and can't be executed on macOS at the moment.

**Comment by philt31** [comment]
okay thanks, I've installed it now on a unix box, but now when I try and run the ./test_PS_modeling.sh I get the following error below. any ideas?

(kmer) (klmf372@asprd0111) - (08:37) - (~/bin/PhenotypeSeeker/example)
-=>>./test_PS_modeling.sh
Downloading the folder with example files ...

--2021-04-01 08:37:25--  http://bioinfo.ut.ee/PhenotypeSeeker/PS_modeling_example_files.tar.gz
Resolving bioinfo.ut.ee... 193.40.23.25
Connecting to bioinfo.ut.ee|193.40.23.25|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://bioinfo.ut.ee/PhenotypeSeeker/PS_modeling_example_files.tar.gz [following]
--2021-04-01 08:37:25--  https://bioinfo.ut.ee/PhenotypeSeeker/PS_modeling_example_files.tar.gz
Connecting to bioinfo.ut.ee|193.40.23.25|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52856987 (50M) [application/x-gzip]
Saving to: `PS_modeling_example_files.tar.gz'

100%[====================================================================================================================================================================================================================================>] 52,856,987  1.73M/s   in 70s

2021-04-01 08:38:36 (735 KB/s) - `PS_modeling_example_files.tar.gz' saved [52856987/52856987]

Unpacking the folder ...

PS_modeling_example_files/
PS_modeling_example_files/VL_0453.fasta
PS_modeling_example_files/VL_0064.fasta
PS_modeling_example_files/VL_0040.fasta
PS_modeling_example_files/VL_0004.fasta
PS_modeling_example_files/VL_0276.fasta
PS_modeling_example_files/VL_0216.fasta
PS_modeling_example_files/VL_0112.fasta
PS_modeling_example_files/VL_0368.fasta
PS_modeling_example_files/VL_0378.fasta
PS_modeling_example_files/VL_0369.fasta
PS_modeling_example_files/VL_0065.fasta
PS_modeling_example_files/VL_0091.fasta
PS_modeling_example_files/VL_0303.fasta
PS_modeling_example_files/VL_0233.fasta
PS_modeling_example_files/VL_0073.fasta
PS_modeling_example_files/VL_0464.fasta
PS_modeling_example_files/VL_0098.fasta
PS_modeling_example_files/VL_0159.fasta
PS_modeling_example_files/VL_0442.fasta
PS_modeling_example_files/VL_0377.fasta
PS_modeling_example_files/VL_0198.fasta
PS_modeling_example_files/VL_0456.fasta
PS_modeling_example_files/VL_0088.fasta
PS_modeling_example_files/VL_0137.fasta
PS_modeling_example_files/VL_0302.fasta
PS_modeling_example_files/VL_0288.fasta
PS_modeling_example_files/VL_0047.fasta
PS_modeling_example_files/VL_0346.fasta
PS_modeling_example_files/VL_0252.fasta
PS_modeling_example_files/VL_0296.fasta
PS_modeling_example_files/VL_0373.fasta
PS_modeling_example_files/VL_0208.fasta
PS_modeling_example_files/VL_0191.fasta
PS_modeling_example_files/VL_0194.fasta
PS_modeling_example_files/VL_0069.fasta
PS_modeling_example_files/VL_0348.fasta
PS_modeling_example_files/VL_0029.fasta
PS_modeling_example_files/VL_0111.fasta
PS_modeling_example_files/VL_0140.fasta
PS_modeling_example_files/VL_0367.fasta
PS_modeling_example_files/data.pheno

Launching the phenotypeseeker modeling:
phenotypeseeker modeling PS_modeling_example_files/data.pheno

######                   PhenotypeSeeker                   ######
######                      modeling                       ######

Generating the k-mer lists for input samples:
	30 of 30 lists generated.
Generating the k-mer feature vector.
Mapping samples to the feature vector space:
	30 of 30 samples mapped.
Estimating the Mash distances between samples...
Calculating the GSC weights from mash distance matrix...
Conducting the k-mer specific chi-square tests:
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
split: invalid option -- 'n'
Try `split --help' for more information.
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/klmf372/.local/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/klmf372/.local/lib/python3.8/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/klmf372/.local/lib/python3.8/site-packages/PhenotypeSeeker/modeling.py", line 638, in get_kmers_tested
    for line in zip(*[open(item) for item in split_of_kmer_lists]):
  File "/home/klmf372/.local/lib/python3.8/site-packages/PhenotypeSeeker/modeling.py", line 638, in <listcomp>
    for line in zip(*[open(item) for item in split_of_kmer_lists]):
FileNotFoundError: [Errno 2] No such file or directory: 'K-mer_lists/VL_0004_mapped_00000'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/klmf372/.local/bin/phenotypeseeker", line 307, in <module>
    Main()
  File "/home/klmf372/.local/bin/phenotypeseeker", line 296, in Main
    func = args.func(args)
  File "/home/klmf372/.local/lib/python3.8/site-packages/PhenotypeSeeker/modeling.py", line 1651, in modeling
    list(map(
  File "/home/klmf372/.local/lib/python3.8/site-packages/PhenotypeSeeker/modeling.py", line 1652, in <lambda>
    lambda x:  x.test_kmers_association_with_phenotype(),
  File "/home/klmf372/.local/lib/python3.8/site-packages/PhenotypeSeeker/modeling.py", line 574, in test_kmers_association_with_phenotype
    pvalues_from_all_threads = Input.pool.map(
  File "/home/klmf372/.local/lib/python3.8/site-packages/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/klmf372/.local/lib/python3.8/site-packages/multiprocess/pool.py", line 768, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'K-mer_lists/VL_0004_mapped_00000'
