### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by gracehm** [bioinfo-ut/PhenotypeSeeker#17]
Hello,
I just started going through the install process for PhenotypeSeeker. I created a new environment and followed the steps provided, but I keep running into the error: 
File "/usr/local/bin/phenotypeseeker", line 13, in <module>
    from PhenotypeSeeker import modeling, prediction, annotation
  File "/usr/local/lib/python3.6/dist-packages/PhenotypeSeeker/modeling.py", line 45, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

Do you have recommendations to fix this? I tried sudo apt-get install matplotlib but did not work.

Thanks.

**Comment by gracehm** [comment]
Solved by going into phenotypeseeker directory and running the command:
sudo apt-get install python3-matplotlib

**Comment by erkiaun** [comment]
Nice that it got solved! Added matplotlib to be installed while installing PhenotypeSeeker!

**Comment by gracehm** [comment]
Hi!
I have one more question for implementing PhenotypeSeeker. Is there an
option for a custom Kmer length or an easy way I can change the code for my
use case for a length of 31? I am struggling to map the Kmer size of 13 to
BLAST hits as there is so much diversity. This would also help me comparing
other software I'm also testing out.

Thanks,
Grace
