### ISSUE TITLE
inconsistency between chi2_results and k-mers_and_coefficients_in_log_reg_model

### ISSUE THREAD

**Issue by rtnakano1984** [bioinfo-ut/PhenotypeSeeker#20]
Hallo! Thanks for building such a nice pipeline! I have used this for my own bacterial genome dataset with binary trait data, and it worked pretty well. However, I found an inconsistency between chi2_results and k-mers_and_coefficients_in_log_reg_model and having a hard time to interpret.  

In chi2_results, I have a number of kmers that are specifically found in one group of genomes but not in the others. This makes perfect sense and the list of strains that have these kmers also nicely match with the trait data. This was very promising. Now, when I looked at the k-mers_and_coefficients_in_log_reg_model file, I also found a number of kmers, but it says ALL kmers are present in ALL genomes. The "No._of_samples_with_k-mer" column showed the same number for all kmers, and this number is the total number of genomes that I fed into the pipeline. I directly compared these two files and found that indeed the kmers shown in the log_reg_model are those that showed low P values in the chi2_results, while the numbers in "num_samples_w_kmer" column in the chi2_results.txt and the "No._of_samples_with_k-mer" column in the k-mers_and_coefficients_in_log_reg_model.txt do not match with each other, even for the kmers with identical sequences.

Am I getting something utterly wrong or missing something? It would be very much appreciated if you could walk me through why this could happen!

Many many thanks,
Thomas

**Comment by erkiaun** [comment]
Hi Ryohei!

I am going to look into it. Probably it is some kind a bug and the info in
chi2 results is the correct one. Could you please specify which version do
you have (phenotypeseeker --version)?

Best regards,
Erki

**Comment by erkiaun** [comment]
Should be fixed now in the latest version 1.0.2.

Erki

**Comment by rtnakano1984** [comment]
Hi Erki! Thanks a lot for your quick work, I confirm that it provides the right values in the log_reg_model results on my side as well. Thanks!!
