### ISSUE TITLE
Is PhenotypeSeeker worth using for eukaryotes?

### ISSUE THREAD

**Issue by shelkmike** [bioinfo-ut/PhenotypeSeeker#24]
In the article, PhenotypeSeeker is described as a tool for bacterial genome analysis. How do you think, could in be used for eukaryotes?

**Comment by bioinfo-ut** [comment]
We have not tested it on eukaryotes.

**Comment by shelkmike** [comment]
Thank you. But do you think there might be some reason why PhenotypeSeeker is not applicable to eukaryotes? I don't see any such reasons.

**Comment by bioinfo-ut** [comment]
Did you mean large eukaryotic genomes? The complexity of eukaryotic genomes is several magnitudes larger, so certainly some filtering is needed to avoid unwanted influences of noise (k-mers originating from sequencing errors, adapters, PCR duplicates). Also, haploid/diploid variants might have unexpected effects. High-copy repeated regions might influence the results. For small eukaryotes (yeasts), it might be fine, though.

**Comment by shelkmike** [comment]
Yes, I thought about trying PhenotypeSeeker for a plant species with 1 Gbp genome.

**Comment by erkiaun** [comment]
Hi Mikhail!

In principle, it should work as well.
By default, it uses 13-mers, which seems to work well with prokaryotes.
However, when trying it on eukaryotes, I would recommend to roughly double the k-mer length.
