### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by ctparson** [bioinfo-ut/PhenotypeSeeker#4]
Following the install instructions everything appears to be running fine with the install, and then it terminates with the following, and attempting version command indicates that install wasn't successful, any suggestions would be greatly appreciated.  

sudo: pip2.7: command not found
sudo: pip2.7: command not found
sudo: pip2.7: command not found
sudo: pip2.7: command not found

**Comment by erkiaun** [comment]
It seems that the pip update brought along the need to change the pip2.7 with pip2 in the install.sh file.
Should work now!
